---
# tasks file for pyenv-ubuntu
- name: Clone pyenv repository
  ghq:
    executable: "{{pyenv_ghq_executable}}"
    name: yyuu/pyenv
    update: yes
- name: Install python build dependencies.
  apt:
    name: "{{item}}"
  with_items:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncurses5-dev
  - libncursesw5-dev
  - xz-utils
  become: "{{pyenv_nonroot}}"
- name: Notice
  debug:
    msg: "export PYENV_ROOT=$GHQ_ROOT/github.com/yyuu/pyenv"
- name: Notice
  debug:
    msg: "export PATH=$PYENV_ROOT/bin:$PATH"
- name: Notice
  debug:
    msg: "eval \"$(pyenv init -)\""
